#!/usr/bin/env python3
#
# Simple program to print the frequency responses of the component for the values from 0 to 1, by 0.001 steps
# made in python 3, you can launch it with:
# ./107transfer [num den]*
# (See subject for more details)
#

import sys
import math
import os
import random

def     man_help():
    print("USAGE")
    print("\t\t./107transfer [num den]*")
    print("DESCRIPTION")
    print("\t\tnum\tpolynomial numerator defined by its coeficients")
    print("\t\tden\tpolynomial denominator defined by its coeficients")

def     valid_string(string):
    i = 0
    while (i < len(string)):
        if (string[i] < '.' and string[i] > '/'
            and string[i] < '0' or string[i] > '9'):
            sys.stdout.write("Invalid argument")
            exit(84)

if (len(sys.argv) >= 2 and (len(sys.argv) - 1) % 2 == 0):

    if (sys.argv[1] == "-h"):
        man_help()
        exit(0)

    a = 1
    x = 0.0
    result = 1.0
    while (x < 1.001):
        while (a < (len(sys.argv) - 1)):
            try:
                num = [int(s) for s in sys.argv[a].split('*')]
                denum = [int(s) for s in sys.argv[a + 1].split('*')]
            except ValueError:
                sys.stdout.write("Invalid argument\n");
                exit(84)
            result = result * (sum(num[i] * x ** i for i in range(len(num))) / sum(denum[i] * x ** i for i in range(len(denum))))
            a = a + 2
        if (round(x, 3) == int(x)):
            print('{} -> {:.5f}'.format(int(x), result))
        else:
            print('{} -> {:.5f}'.format(round(x, 3), result))
        x += 0.001
        a = 1
        result = 1.0
            
else:
    sys.stdout.write("Invalid number of argument\n")
    exit(84)
