#!/usr/bin/python2.7
#
# Simple program to calcul vectors
# made in python 2.7, you can launch it with:
# ./101pong x0 y0 z0 x1 y1 z1 time
# (See subject for more details)
#

import sys
import math
import string

i = 1

if (len(sys.argv) != 8):
    exit (84)

if (sys.argv[7] < 0):
    exit (84)

while (i < len(sys.argv)):
    j = 0
    while (j < len(sys.argv[i])):
        if (ord(sys.argv[i][j]) < ord('-') or
            ord(sys.argv[i][j]) > ord('9') or
            ord(sys.argv[i][j]) == ord('/')):
           exit (84)
        j = j + 1
    i = i + 1;

x0      = float(sys.argv[1])
y0      = float(sys.argv[2])
z0      = float(sys.argv[3])
x1      = float(sys.argv[4])
y1      = float(sys.argv[5])
z1      = float(sys.argv[6])
n       = int(sys.argv[7])

x       = x1 - x0
y       = y1 - y0
z       = z1 - z0

coord_x = x1 + (x * n)
coord_y = y1 + (y * n)
coord_z = z1 + (z * n)

power   = (((y)**2) + ((x)**2) + ((z)**2))
if (power == 0):
    norm = 0
else:
    norm    = math.sqrt(power)
    radian  = math.asin(math.sqrt(z**2) / norm)
    angle   = math.degrees(radian)

print str("The speed vector coordinates are :")
print str('(') + "%.2f" % x + str(';') + "%.2f" % y + str(';') + "%.2f" % z + str(')')
print str("At time t+") + "%.0f" % n + str(", ball coordinates will be :")
print str('(') + "%.2f" % coord_x + str(';') + "%.2f" % coord_y + str(';') + "%.2f" % coord_z + str(')')

if ((z1 >= 0 and z < 0) or (z1 <= 0 and z > 0)):
    print str("The incidence angle is :")
    print "%.2f" % angle + str(" degrees")
else:
    print str("The ball won't reach the bat.")
